#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "codedark"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    statusline_unicode_symbols = true
    # Enable vim compatible mode, avoid changing origin vim key bindings
    # vimcompatible = true
    # Set the default indent to 4 space
    default_indent = 4
    # Enable bootstrap function
    bootstrap_before = "myspacevim#before"
    bootstrap_after  = "myspacevim#after"
    # Move the file tree to the left
    filetree_direction = "left"
    # Set the windows manager leader key to "."
    windows_leader = "."
    # Set the default autocomplete method to deoplete
    autocomplete_method = "deoplete"
    # Enable file type icons for file manager
    enable_vimfiler_filetypeicon = true
    # Disable cursorline
    enable_cursorline = false
    # Disable auto complete parens
    autocomplete_parens = false
    
    # Status line color scheme TODO: Set gui color scheme
    custom_color_palette = [
        ["#282828", "#a89984", 39, 235],
        ["#a89984", "#504945", 239, 188],
        ["#a89984", "#3c3836", 237, 188],
        ["#665c54", 235],
        ["#282828", "#83a598", 235, 114],
        ["#282828", "#fe8019", 235, 170],
        ["#282828", "#8ec07c", 235, 108],
        ["#282828", "#689d6a", 235, 72],
        ["#282828", "#8f3f71", 235, 132],
    ]

# Add Vim Code Dark Theme
[[custom_plugins]]
    repo = "tomasiser/vim-code-dark"
    merged = false

# Add transparent background plugin
[[custom_plugins]]
    repo = "starunity/seiya.vim"
    merged = false

# GitHub copilot
[[custom_plugins]]
    repo = "github/copilot.vim"
    merged = false

# Add smart auto complete plugin 
[[custom_plugins]]
   name = "tbodt/deoplete-tabnine"
   build = "./install.sh"
   merged = false

# Add translation plugin
[[custom_plugins]]
    name = "voldikss/vim-translator"
    merged = false

# Add Display Color plugin
[[custom_plugins]]
    name = "lilydjwg/colorizer"
    merged = false

# [[custom_plugins]]
    # name = "luochen1990/rainbow"
    # merged = false

[[custom_plugins]]
    name = "gcmt/wildfire.vim"
    merged = false

[[custom_plugins]]
    name = "lilydjwg/fcitx.vim"
    merged = false

[[custom_plugins]]
    name = "ferrine/md-img-paste.vim"
    merged = false

# Config core layer
[[layers]]
    name = 'core'
    # Showing hidden file in filetree
    filetree_show_hidden = true
    # Disabled smooth scrolling key bindings
    enable_smooth_scrolling = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
autocomplete_parens = false
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

# Enable vim shell layers
[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# Enable git layer
[[layers]]
    name = "git"

# Enable sudo layer
[[layers]]
    name = "sudo"

# Enable Fuzzy finder
[[layers]]
    name = "denite"

# Language Layers

# Add toml highlight support
[[layers]]
    name = "lang#toml"

# Add language server protocol support
[[layers]]
    name = 'lsp'
    # enabled_clients = ['clangd']
    # enabled_clients = ['jdtls']
    enabled_clients = ['jedi_language_server']

# Add code format support
[[layers]]
    name = "format"

# Add code debug support
# [[layers]]
   # name = "debug"

[[layers]]
  name = "lang#markdown"
  enabled_formater = ["prettier"]

# C
# [[layers]]
    # name = "lang#c"
    # format_on_save = true
    # [layer.clang_std]
        # c = "c11"


# Python
[[layers]]
    name = "lang#python"
    format_on_save = true

# Java
# [[layers]]
    # name = "lang#java"
    # format_on_save = true

# Docker
# [[layers]]
    # format_on_save = true
    # name = "lang#dockerfile"

